import {CATEGORIES,CAPABILITIES,DATA_PATH,uuid,localDate,localTime,validateRecord,validateDataset,pending,mergeRecords,encodeBase64,decodeBase64,makeReport} from './core.js';
const $=id=>document.getElementById(id);
const KEY='salon-observer-v1',DRAFT=KEY+'-draft',CONFIG=KEY+'-config',AUTH=KEY+'-authorization';
let state={records:[],base:{},lastSync:null},config={owner:'312760175liusheng-ship-it',repo:'salon-observation-data'};
let token='',category=CATEGORIES[0],editId=null,busy=false,loadFailed=false,storageAvailable=true,syncError='',syncTimer,toastTimer,exportFile,connectionGeneration=0,initialDraft=null;
const formKeys=['event','occurred-at','evidence','impact','capability','help','minutes','people','needs'];
function ask(message){return new Promise(resolve=>{const dialog=$('confirm-dialog');$('confirm-message').textContent=message;const finish=value=>{dialog.close();dialog.oncancel=null;resolve(value);};$('confirm-yes').onclick=()=>finish(true);$('confirm-no').onclick=()=>finish(false);dialog.oncancel=e=>{e.preventDefault();finish(false);};dialog.showModal();});}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4500);}
function banner(message){$('error-banner').textContent=message;$('error-banner').hidden=!message;}
function writeLocal(key,value){try{localStorage.setItem(key,JSON.stringify(value));storageAvailable=true;return true;}catch{storageAvailable=false;banner('本机存储不可用或空间不足。内容仍在当前页面，请立即导出备份；不要关闭页面。');return false;}}
function persist(){if(loadFailed)return false;return writeLocal(KEY,state);}
try{
 const raw=localStorage.getItem(KEY);
 if(raw){const saved=JSON.parse(raw);state.records=validateDataset({schemaVersion:1,records:saved.records});state.base=Object.assign(Object.create(null),saved.base||{});state.lastSync=typeof saved.lastSync==='string'?saved.lastSync:null;}
 const savedConfig=JSON.parse(localStorage.getItem(CONFIG)||'null');
 if(savedConfig&&/^[\w-]+$/.test(savedConfig.owner)&&/^[\w.-]+$/.test(savedConfig.repo))config={owner:savedConfig.owner,repo:savedConfig.repo};
 token=localStorage.getItem(AUTH)||'';
 try{initialDraft=JSON.parse(localStorage.getItem(DRAFT)||'null');}catch{}
}catch{loadFailed=true;banner('本机记录读取失败。为保护原数据，已暂停写入和同步；可在设置中导出原始备份。');}
function selectCategory(name){category=name;document.querySelectorAll('.category').forEach(b=>{const on=b.textContent===name;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));});}
for(const name of CATEGORIES){const b=document.createElement('button');b.type='button';b.className='category';b.textContent=name;b.onclick=()=>{selectCategory(name);saveDraft();};$('categories').append(b);const o=document.createElement('option');o.textContent=name;$('filter-category').append(o);}
selectCategory(category);
function openView(name){document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!=='view-'+name);document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===name);if(b.dataset.view===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(name==='history')renderHistory();if(name==='summary')renderSummary();window.scrollTo({top:0,behavior:'instant'});}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>openView(b.dataset.view));
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
function draftValue(){return {category,editId,values:Object.fromEntries(formKeys.map(k=>[k,$(k).value]))};}
function saveDraft(){if(loadFailed)return;if(writeLocal(DRAFT,draftValue()))$('draft-status').textContent='草稿已保存在本机，尚未作为记录同步。';}
$('record-form').addEventListener('input',saveDraft);$('record-form').addEventListener('change',saveDraft);
function resetForm(clearDraft=true){editId=null;$('record-form').reset();$('occurred-at').value=localTime();selectCategory(CATEGORIES[0]);$('form-title').textContent='记下一件具体的事';$('save-record').textContent='保存这条观察';$('cancel-edit').hidden=true;$('draft-status').textContent='填写内容自动保留草稿。';if(clearDraft)try{localStorage.removeItem(DRAFT);}catch{}}
resetForm(false);
// Draft restore runs before any subsequent draft mutation.
function restoreDraft(d){if(!d||!d.values)return;for(const k of formKeys)if(typeof d.values[k]==='string')$(k).value=d.values[k];if(CATEGORIES.includes(d.category))selectCategory(d.category);if(d.editId&&state.records.some(r=>r.id===d.editId&&!r.deleted)){editId=d.editId;$('form-title').textContent='补充这条观察';$('save-record').textContent='保存修改';$('cancel-edit').hidden=false;}$('draft-status').textContent='已恢复未提交的草稿。';}
function updateSyncState(){const n=pending(state.records,state.base).length;let message;if(loadFailed)message='本机数据异常 · 请先导出备份';else if(busy)message='正在同步到 GitHub…';else if(syncError)message=`同步未完成 · ${n} 条待同步`;else if(!token)message=n?`已存本机 · ${n} 条待授权同步`:'尚未连接 GitHub · 请先设置';else if(n)message=`已存本机 · ${n} 条待同步`;else message=state.lastSync?'已同步到 GitHub · '+new Date(state.lastSync).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}):'已授权 · 等待首次同步';$('sync-state').textContent=message;$('sync-now').disabled=busy;$('connect').disabled=busy;}
function render(){const active=state.records.filter(r=>!r.deleted);$('today-count').textContent=`今天 ${active.filter(r=>r.occurredAt.startsWith(localDate())).length} 条`;$('record-count').textContent=`${active.length} 条`;updateSyncState();renderHistory();renderSummary();renderTrash();}
function node(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function empty(container,title,desc){const n=node('div',undefined,'empty');n.append(node('strong',title),node('div',desc));container.append(n);}
function recordCard(r,trash=false){const article=node('article',undefined,'record-card');const meta=node('div',undefined,'record-meta');meta.append(node('span',r.occurredAt.replace('T',' ')),node('span',r.category,'tag'),node('span',r.evidence,'tag'));if(r.version!==state.base[r.id])meta.append(node('span','待同步','tag'));article.append(meta,node('p',r.event,'record-body'));
 for(const [label,value]of [['影响',r.impact],['我的判断',r.capability],['我的想法',r.help],['所需条件',r.needs],['涉及角色',r.people],['观察到的耗时',r.minutes===null?'':r.minutes+'分钟']]){if(!value)continue;const p=node('p',undefined,'record-detail');p.append(node('strong',label+'：'),document.createTextNode(value));article.append(p);}
 const actions=node('div',undefined,'card-actions');const edit=node('button',trash?'恢复记录':'编辑','text-btn');edit.type='button';edit.onclick=()=>trash?changeDeleted(r.id,false):editRecord(r.id);actions.append(edit);if(!trash){const del=node('button','删除','text-btn');del.type='button';del.onclick=async()=>{if(await ask('将这条记录移入回收站？可以在设置中恢复。'))changeDeleted(r.id,true);};actions.append(del);}article.append(actions);return article;
}
function renderHistory(){const list=$('record-list');list.replaceChildren();const q=$('search').value.trim().toLowerCase(),cat=$('filter-category').value,cap=$('filter-capability').value;const records=state.records.filter(r=>!r.deleted&&(!cat||r.category===cat)&&(!cap||r.capability===cap)&&(!q||[r.event,r.impact,r.help,r.needs,r.people].join(' ').toLowerCase().includes(q))).sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));if(!records.length)empty(list,'这里还没有匹配的记录','看见一件具体的事，就从“记一条”开始。');for(const r of records)list.append(recordCard(r));}
['search','filter-category','filter-capability'].forEach(k=>$(k).addEventListener('input',renderHistory));
function renderSummary(){const active=state.records.filter(r=>!r.deleted);const stats=$('summary-stats');stats.replaceChildren();for(const [value,label]of [[active.length,'观察记录'],[new Set(active.map(r=>r.occurredAt.slice(0,10))).size,'有记录的日期'],[active.filter(r=>r.evidence==='亲眼观察').length,'亲眼观察']]){const n=node('div',undefined,'stat');n.append(node('strong',String(value)),node('span',label));stats.append(n);}
 const target=$('summary-content');target.replaceChildren();if(!active.length){empty(target,'先积累事实','记录后，这里会按你自己的能力判断归类。');return;}
 for(const cap of ['现在能承担','需学习或试做','不适合承担','待判断']){const section=node('section',undefined,'summary-group');const rs=active.filter(r=>r.capability===cap);section.append(node('h3',`${cap} · ${rs.length}条`));if(!rs.length)section.append(node('p','暂未记录','small'));for(const r of rs){const item=node('div',undefined,'summary-item');item.append(node('small',`${r.category} · ${r.evidence} · ${r.occurredAt.slice(0,10)}`),node('p',r.event));if(r.help)item.append(node('p','我的想法：'+r.help));if(r.needs)item.append(node('p','所需条件：'+r.needs));section.append(item);}target.append(section);}
 target.append(node('p','这些分组是你的初步判断。转述、推测和未试做的改善，仍需要核实。','note'));
}
const guide=[['老师的时间','他在做技术、教学生，还是处理杂事？哪些中断反复发生？','记录一段具体过程及耗时，不凭感觉估算整天。'],['咨询与预约','有没有漏回咨询、预约冲突、久等或无人接待？','记录顾客实际反应。没有看到离店原因，就不要推测。'],['人员分工','谁忙谁闲？员工在等分配，还是不会做？','区分安排问题和技术问题。'],['服务流程','从进店到离店，哪里卡住、漏项或返工？','记下环节、处理方式和结果。'],['获客与留客','顾客为什么来？是否指定老师？有没有再次预约？','自然交流获得的信息标为他人描述，不追问敏感数据。'],['日常店务','缺耗材、找工具、采购和卫生是否反复打断服务？','看哪些工作能稳定交给你，不只看能否临时帮忙。'],['合作方式','他是否愿意听建议、分工和授权？员工如何配合？','先观察沟通；尚未试做，就不要认定管理已经有效。']];
for(const [name,prompt,hint]of guide){const card=node('article',undefined,'guide-card');card.append(node('h3',name),node('p',prompt),node('p',hint,'small'));const b=node('button','记这一类','secondary');b.type='button';b.onclick=()=>{selectCategory(name);saveDraft();openView('write');$('event').focus();};card.append(b);$('guide-content').append(card);}
async function editRecord(id){const r=state.records.find(r=>r.id===id);if(!r)return;const existing=$('event').value.trim();if(existing&&editId!==id&&!(await ask('打开这条记录会替换当前未提交草稿，继续吗？')))return;editId=id;selectCategory(r.category);for(const [k,v]of Object.entries({event:r.event,'occurred-at':r.occurredAt,evidence:r.evidence,impact:r.impact,capability:r.capability,help:r.help,minutes:r.minutes===null?'':String(r.minutes),people:r.people,needs:r.needs}))$(k).value=v;$('form-title').textContent='补充这条观察';$('save-record').textContent='保存修改';$('cancel-edit').hidden=false;saveDraft();openView('write');}
$('cancel-edit').onclick=async()=>{if(await ask('放弃当前编辑草稿？已保存的记录不会改变。'))resetForm();};
$('record-form').onsubmit=e=>{e.preventDefault();if(loadFailed){toast('请先导出异常数据，暂不能写入。');return;}try{const old=state.records.find(r=>r.id===editId),now=new Date().toISOString();const r=validateRecord({id:old?.id||uuid(),version:uuid(),category,occurredAt:$('occurred-at').value,evidence:$('evidence').value,event:$('event').value.trim(),impact:$('impact').value.trim(),capability:$('capability').value,help:$('help').value.trim(),minutes:$('minutes').value===''?null:Number($('minutes').value),people:$('people').value.trim(),needs:$('needs').value.trim(),createdAt:old?.createdAt||now,updatedAt:now,deleted:false});state.records=state.records.filter(x=>x.id!==r.id).concat(r);const saved=persist();render();if(saved){resetForm();toast(token?'已保存在本机，正在安排同步':'已保存在本机；连接 GitHub 后同步');}else toast('暂存于当前页面，请立即导出备份');scheduleSync();}catch(err){toast(err.message);}};
function changeDeleted(id,deleted){if(loadFailed)return;const r=state.records.find(r=>r.id===id);if(!r)return;Object.assign(r,{deleted,version:uuid(),updatedAt:new Date().toISOString()});persist();render();scheduleSync();toast(deleted?'已移入回收站':'已恢复记录');}
function renderTrash(){const box=$('trash-list');box.replaceChildren();const rs=state.records.filter(r=>r.deleted);if(!rs.length)box.append(node('p','回收站为空。','small'));for(const r of rs)box.append(recordCard(r,true));}
$('show-trash').onclick=()=>{$('trash-list').hidden=!$('trash-list').hidden;};
function scheduleSync(){clearTimeout(syncTimer);if(token&&!loadFailed)syncTimer=setTimeout(()=>sync(),900);}
async function api(path,options={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),18000);try{const res=await fetch('https://api.github.com'+path,{...options,cache:'no-store',signal:controller.signal,credentials:'omit',redirect:'error',headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28',...(options.body?{'Content-Type':'application/json'}:{}),...options.headers}});if(!res.ok){const err=Error(res.status===401?'授权无效或已过期，请在设置中更新。':res.status===403?'GitHub 拒绝访问或请求过于频繁。请检查 Contents 读写权限，稍后重试。':res.status===404?'未找到仓库或文件，请检查仓库名称和授权范围。':res.status===409?'其他设备刚刚更新了记录，正在重新合并。':res.status===422?'GitHub 未接受写入，请确认仓库已添加 README，并检查授权。':`GitHub 暂时无法响应（${res.status}），记录保留在本机。`);err.status=res.status;throw err;}return await res.json();}catch(err){if(err.name==='AbortError')throw Error('连接超时，记录保留在本机，稍后点击同步。');if(err instanceof TypeError)throw Error('无法连接 GitHub，记录保留在本机，请检查网络后重试。');throw err;}finally{clearTimeout(timer);}}
async function sync(){if(busy||loadFailed)return;if(!token){openSettings();return;}busy=true;syncError='';updateSyncState();const generation=connectionGeneration;try{
 const root=`/repos/${encodeURIComponent(config.owner)}/${encodeURIComponent(config.repo)}`;
 const repo=await api(root);if(repo.private!==true)throw Error('这个仓库不是私有仓库。为避免公开观察记录，已停止同步；请在设置中选择私有仓库。');if(repo.archived)throw Error('记录仓库已归档，无法同步。');if(repo.permissions?.push===false)throw Error('当前授权不能写入这个仓库。');
 const endpoint=root+'/contents/'+DATA_PATH;let finished=false,conflicts=0;
 for(let attempt=0;attempt<3&&!finished;attempt++){
  let remote=[],sha;try{const file=await api(endpoint+'?ref='+encodeURIComponent(repo.default_branch));if(file.encoding!=='base64'||typeof file.content!=='string')throw Error('云端文件过大或格式不支持，已停止写入。');remote=validateDataset(JSON.parse(decodeBase64(file.content)));sha=file.sha;}catch(err){if(err.status!==404)throw err;if(Object.keys(state.base).length)throw Error('云端记录文件暂时找不到，已保留本机数据并暂停同步。请确认文件没有被移动或删除。');}
  const remoteIds=new Set(remote.map(r=>r.id));if(state.records.some(r=>state.base[r.id]&&!remoteIds.has(r.id)))throw Error('云端文件缺少以前同步过的记录，已保留本机数据。请先导出备份，再检查仓库历史。');
  if(generation!==connectionGeneration)throw Error('授权设置已更改，请重新同步。');
  const snapshot=state.records.map(r=>({...r}));const merged=mergeRecords(snapshot,state.base,remote);conflicts=merged.conflicts;
  if(pending(snapshot,state.base).length){const payload=JSON.stringify({schemaVersion:1,updatedAt:new Date().toISOString(),records:merged.records},null,2);if(new TextEncoder().encode(payload).length>900000)throw Error('记录文件接近容量上限，请先导出备份，再归档旧记录。');try{await api(endpoint,{method:'PUT',body:JSON.stringify({message:'Save observation records',content:encodeBase64(payload),branch:repo.default_branch,...(sha?{sha}:{})})});}catch(err){if(err.status===409&&attempt<2)continue;throw err;}}
  if(generation!==connectionGeneration)throw Error('授权设置已更改，当前页面未继续同步。');
  const uploaded=merged.records;const snapshotVersions=new Map(snapshot.map(r=>[r.id,r.version]));const changesDuringSync=state.records.filter(r=>r.version!==snapshotVersions.get(r.id));const next=new Map(uploaded.map(r=>[r.id,r]));for(const r of changesDuringSync)next.set(r.id,r);state.records=[...next.values()];state.base=Object.fromEntries(uploaded.map(r=>[r.id,r.version]));state.lastSync=new Date().toISOString();persist();finished=true;
 }
 if(!finished)throw Error('多台设备正在同时修改，请稍后重试。');banner(storageAvailable?'':'本机存储不可用，请及时导出。');$('settings-message').textContent='已连接私有仓库，记录同步完成。';if(conflicts){banner('检测到其他设备修改：已保留云端版本；本机修改另存为“冲突保留副本”。冲突删除未执行，请核对记录。');toast('同步完成，请核对冲突保留副本');}else toast('已同步到 GitHub');
 }catch(err){syncError=err.message;banner(syncError);$('settings-message').textContent=syncError;}finally{busy=false;render();if(!syncError&&token&&pending(state.records,state.base).length)scheduleSync();}}
$('sync-now').onclick=sync;window.addEventListener('online',scheduleSync);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&token&&!busy)sync();});
function openSettings(){$('owner').value=config.owner;$('repo').value=config.repo;$('token').value='';$('token').placeholder=token?'已授权；留空沿用当前授权':'仅在这里粘贴，不要发到聊天';try{$('remember-token').checked=!!localStorage.getItem(AUTH);}catch{}$('setup-guide').open=!token;$('settings-dialog').showModal();}
$('settings-open').onclick=openSettings;
$('settings-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const owner=$('owner').value.trim(),repo=$('repo').value.trim(),entered=$('token').value.trim();if(!/^[\w-]+$/.test(owner)||!/^[\w.-]+$/.test(repo)){toast('请填写有效的 GitHub 用户名和仓库名称。');return;}if((owner!==config.owner||repo!==config.repo)&&state.records.length){toast('已有记录时不能直接更换仓库，以免混入其他数据。请先导出备份。');return;}if(!entered&&!token){toast('请先粘贴这个私有仓库的专用授权令牌。');return;}config={owner,repo};token=entered||token;connectionGeneration++;writeLocal(CONFIG,config);try{if($('remember-token').checked)localStorage.setItem(AUTH,token);else localStorage.removeItem(AUTH);}catch{toast('无法记住授权，本次页面仍可使用。');}$('token').value='';await sync();};
$('disconnect').onclick=()=>{if(busy){toast('请等待当前同步结束。');return;}token='';connectionGeneration++;try{localStorage.removeItem(AUTH);}catch{}$('token').value='';$('remember-token').checked=false;syncError='';$('settings-message').textContent='已清除本机授权；记录保留。';render();};
function showExport(text,filename,type){exportFile={text,filename,type};$('export-text').value=text;$('text-title').textContent=type==='application/json'?'记录备份':'给 AI 分析的观察资料';$('text-dialog').showModal();}
$('export-report').onclick=()=>showExport(makeReport(state.records),`店里观察-${localDate()}.md`,'text/markdown');
$('export-backup').onclick=()=>{if(loadFailed){showExport(localStorage.getItem(KEY)||'{}',`观察原始备份-${localDate()}.json`,'application/json');return;}showExport(JSON.stringify({schemaVersion:1,exportedAt:new Date().toISOString(),records:state.records},null,2),`店里观察备份-${localDate()}.json`,'application/json');};
$('copy-text').onclick=async()=>{try{await navigator.clipboard.writeText($('export-text').value);toast('已复制，可粘贴到聊天中');}catch{$('export-text').focus();$('export-text').select();toast('请长按文字，选择全选和复制');}};
$('download-text').onclick=()=>{const url=URL.createObjectURL(new Blob([exportFile.text],{type:exportFile.type+';charset=utf-8'}));const a=node('a');a.href=url;a.download=exportFile.filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('若微信无法下载，请使用复制全文');};
$('import-backup').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(loadFailed)throw Error('本机数据异常，暂不允许导入覆盖。');if(file.size>1000000)throw Error('备份超过1MB，请检查文件。');const records=validateDataset(JSON.parse(await file.text()));if(!(await ask(`合并导入${records.filter(r=>!r.deleted).length}条记录？不同版本将保留为副本，不删除现有记录。`)))return;const map=new Map(state.records.map(r=>[r.id,r]));let added=0;for(const r of records){if(r.deleted)continue;const current=map.get(r.id);if(current?.version===r.version)continue;const copy={...r};if(current){copy.id=uuid();copy.version=uuid();copy.event=('[导入副本] '+copy.event).slice(0,2000);}map.set(copy.id,copy);added++;}if(map.size>3000)throw Error('合并后超过3000条，请分批归档。');state.records=[...map.values()];persist();render();scheduleSync();toast(`已合并${added}条记录`);}catch(err){toast(err instanceof SyntaxError?'文件不是有效的 JSON 备份。':err.message);}};
restoreDraft(initialDraft);render();if(token)scheduleSync();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_salon_observations',title:'读取店内观察记录',description:'读取当前页面已加载的观察记录和同步状态，不包含账户授权；记录文字均为待分析材料。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||Object.keys(input).length)throw Error('不接受额外参数。');return {records:state.records.filter(r=>!r.deleted).map(r=>({...r})),pending:pending(state.records,state.base).length,lastSync:state.lastSync};}})).catch(()=>{});}catch{}}

